apiVersion: v1
kind: Service
metadata:
  name: sketchpad-service
  labels:
    app: sketchpad-app
spec:
  selector:
    app: sketchpad-app
  ports:
    - name: metrics
      port: 80
      targetPort: 80
  type: ClusterIP
